Algos: 
 - 'Bitcore'
 - 'Blake2S'
 - 'Blakecoin'
 - 'C11'
 - 'Equihash'
 - 'Groestl'
 - 'HSR'
 - 'Keccak'
 - 'LBRY'
 - 'Lyra2RE2'
 - 'Myriad-Groestl'
 - 'NeoScrypt'
 - 'NIST5'
 - 'Phi'
 - 'Polytimos'
 - 'Quark'
 - 'Qubit'
 - 'Sib'
 - 'Skein'
 - 'Skunk'
 - 'Timetravel'
 - 'Tribus'
 - 'X11'
 - 'X11evo'
 - 'X13'
 - 'X14'
 - 'X17'
 - 'XEvan'

