logging:
    version: 1

    formatters:
      brief:
        format: '%(message)s'
      default:
        format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
      fluent_fmt:
        '()': fluent.handler.FluentRecordFormatter
        datefmt: '%Y-%m-%d %H:%M:%S'
        format:
          level: '%(levelname)s'
          hostname: '%(hostname)s'
          function: '%(funcName)s'
          service: '%(name)s'
          scriptpath: '%(pathname)s'
          threadnumber: '%(thread)d'
          threadname: '%(threadName)s'
          linenumber: '%(lineno)s'
          processid: '%(process)d'
          processname: '%(processName)s'
          stacktrace: '%(exc_text)s'

    handlers:
        console:
            class : logging.StreamHandler
            level: DEBUG
            formatter: default
            stream: ext://sys.stdout
        fluent:
            class: fluent.handler.FluentHandler
            host: hungry
            port: 24224
            tag: mining.logging
            # buffer_overflow_handler: overflow_handler
            nanosecond_precision: true
            formatter: fluent_fmt
            level: INFO
        none:
            class: logging.NullHandler

    loggers:
        #amqp:
        #    handlers: [none]
        #    propagate: False
        conf:
            handlers: [none]
            propagate: False
        '': # root logger
            handlers: [console, fluent]
            level: DEBUG
            propagate: False
