pools:
    version: 1
    
    poolDefs:
      - name: 'zpool'
        class: 'pool.yiimp'
        apiUrl: 'https://zpool.ca/api/status'
        stratumUrl: '{ALGO}.mine.zpool.ca:{PORT}'
        statsData: 'estimate_last24h'
        cryptoPaid: 'BTC'
        algoMap:
        - ['Buttcore','bitcore']
        - ['Blake2S','blake2s',-3]
        - ['Blakecoin', 'blakecoin',-3]
        - ['C11', 'c11']
        - ['Equihash','equihash',3]
        - ['Groestl','groestl']
        - ['HSR','hsr']
        - ['Keccak','keccak',-3]
        - ['LBRY','lbry']
        - ['Lyra2RE2','lyra2v2']
        - ['Myriad-Groestl','myr-gr']
        - ['NeoScrypt','neoscrypt']
        - ['NIST5','nist5']
        - ['Phi','phi']
        - ['Polytimos','polytimos']
        - ['Quark','quark',-3]
        - ['Qubit','qubit',-3]
        - ['Sib','sib']
        - ['Skein','skein']
        - ['Skunk','skunk']
        - ['Timetravel','timetravel']
        - ['Tribus','tribus']
        - ['X11','x11',-3]
        - ['X11evo','x11evo']
        - ['X13','x13']
        - ['X14','x14']
        - ['X17','x17']
        - ['XEvan','xevan']
      - name: 'ahashpool'
        class: 'pool.yiimp'
        apiUrl: 'https://www.ahashpool.com/api/status'
        stratumUrl: '{ALGO}.mine.ahashpool.com:{PORT}'
        statsData: 'estimate_last24h'
        cryptoPaid: 'BTC'
        algoMap:
        - ['Bitcore','bitcore']
        - ['Blake2S','blake2s',-3]
        - ['Blakecoin', 'blakecoin',-3]
        - ['C11', 'c11']
        - ['Equihash','equihash',3]
        - ['Groestl','groestl']
        - ['HSR','hsr']
        - ['Keccak','keccak',-3]
        - ['LBRY','lbry']
        - ['Lyra2RE2','lyra2v2']
        - ['Myriad-Groestl','myr-gr']
        - ['NeoScrypt','neoscrypt']
        - ['NIST5','nist5']
        - ['Phi','phi']
        - ['Polytimos','polytimos']
        - ['Quark','quark',-3]
        - ['Qubit','qubit',-3]
        - ['Sib','sib']
        - ['Skein','skein']
        - ['Skunk','skunk']
        - ['Timetravel','timetravel']
        - ['Tribus','tribus']
        - ['X11','x11',-3]
        - ['X11evo','x11evo']
